<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="architectureDecisionRecord" nsURI="http://vitruv.tools/architectureDecisionRecord"
    nsPrefix="architectureDecisionRecord">
  <eClassifiers xsi:type="ecore:EClass" name="ADRRepository">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adIssues" upperBound="-1"
        eType="#//ADIssue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADIssue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" lowerBound="1" eType="#//Role"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="motivation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recommendation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backgroundReading" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isSolvedBy" upperBound="-1"
        eType="#//ADAlternative" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasOutcome" eType="#//ADOutcome"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" eType="#//ADDesignElementType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ticketID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADAlternative">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pros" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cons" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="knownUses" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backgroundReading" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="impacts" upperBound="-1"
        eType="#//ADDesignElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADOutcome">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="justification" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assumptions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consequences" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chooses" eType="#//ADAlternative"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decisionStatus" eType="#//DecisionStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ADDesignElementType">
    <eLiterals name="MICROSERVICE"/>
    <eLiterals name="SERVICE_API" value="1"/>
    <eLiterals name="PACKAGE" value="2"/>
    <eLiterals name="MODULE" value="3"/>
    <eLiterals name="CLASS" value="4"/>
    <eLiterals name="INTERFACE" value="5"/>
    <eLiterals name="ENUM" value="6"/>
    <eLiterals name="METHOD" value="7"/>
    <eLiterals name="FIELD" value="8"/>
    <eLiterals name="DATABASE_TABLE" value="9"/>
    <eLiterals name="DATABASE_COLUMN" value="10"/>
    <eLiterals name="CONFIGURATION_ITEM" value="11"/>
    <eLiterals name="DEPLOYMENT_NODE" value="12"/>
    <eLiterals name="OTHER" value="13"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DecisionStatus">
    <eLiterals name="PROPOSED"/>
    <eLiterals name="ACCEPTED" value="1"/>
    <eLiterals name="REJECTED" value="2"/>
    <eLiterals name="DEPRECATED" value="3"/>
    <eLiterals name="SUPERSEDED" value="4"/>
    <eLiterals name="OBSOLETE" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ADDesignElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referencedQualifiedName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="additionalInformation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>