<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="c1" nsURI="http://vitruv.tools/c1" nsPrefix="c1">
  <eClassifiers xsi:type="ecore:EClass" name="C1Repository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="softwareSystems" upperBound="-1"
        eType="#//SoftwareSystem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
        eType="#//Person" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//Reference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareSystem" eSuperTypes="#//C1ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isExternal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" eSuperTypes="#//C1ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//C1ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference1" lowerBound="1"
        eType="#//C1ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference2" lowerBound="1"
        eType="#//C1ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="C1ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
