<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="c2" nsURI="http://vitruv.tools/c2"
  nsPrefix="c2">
  <eClassifiers xsi:type="ecore:EClass" name="C2Repository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
      eType="#//Relationship" containment="true" />
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" upperBound="-1"
      eType="#//Container" containment="true" />
    <eStructuralFeatures xsi:type="ecore:EReference" name="systems" upperBound="-1"
      eType="#//System" containment="true" />
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
      eType="#//Person" containment="true" />
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ContainerType" />
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" upperBound="-1"
      eType="#//Container" />
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container" eSuperTypes="#//C2ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ContainerType" />
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" eSuperTypes="#//C2ModelElement" />
  <eClassifiers xsi:type="ecore:EClass" name="C2ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship" eSuperTypes="#//C2ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference1" lowerBound="1"
      eType="#//C2ModelElement" />
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference2" lowerBound="1"
      eType="#//C2ModelElement" />
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//C2ModelElement" />
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContainerType">
    <eLiterals name="SOFTWARE_SYSTEM" />
    <eLiterals name="OBJECT_STORAGE" value="1" />
    <eLiterals name="DIRECTORY" value="2" />
    <eLiterals name="DATABASE" value="3" />
    <eLiterals name="SERVER_SIDE_APPLICATION" value="4" />
    <eLiterals name="SINGLE_PAGE_APPLICATION" value="5" />
  </eClassifiers>
</ecore:EPackage>